import { z } from "zod";

export const modeSchema = z.enum(["in_person", "hybrid", "online", "unknown"]);
export const confidenceSchema = z.enum(["low", "medium", "high"]);
export const reviewStatusSchema = z.enum([
  "candidate",
  "needs_review",
  "reviewed",
  "rejected",
]);

export const feeSchema = z.object({
  label: z.string().min(1),
  amount: z.number().nonnegative().nullable(),
  currency: z.string().min(3).max(3),
});

export const conferenceSchema = z.object({
  id: z.string().min(1),
  slug: z.string().min(1),
  title: z.string().min(1),
  acronym: z.string().nullable(),
  year: z.number().int().min(2000).max(2100),
  description: z.string(),
  field_tags: z.array(z.string()),
  theme_tags: z.array(z.string()),
  organizer: z.string().nullable(),
  website_url: z.string().url(),
  cfp_url: z.string().url().nullable(),
  source_urls: z.array(z.string().url()).min(1),
  country: z.string(),
  city: z.string(),
  venue: z.string().nullable(),
  mode: modeSchema,
  event_start_date: z.string().nullable(),
  event_end_date: z.string().nullable(),
  submission_deadline: z.string().nullable(),
  abstract_deadline: z.string().nullable(),
  poster_deadline: z.string().nullable(),
  notification_date: z.string().nullable(),
  camera_ready_deadline: z.string().nullable(),
  registration_deadline: z.string().nullable(),
  early_bird_deadline: z.string().nullable(),
  fees: z.array(feeSchema),
  currency: z.string().nullable(),
  student_fee: z.number().nullable(),
  regular_fee: z.number().nullable(),
  virtual_fee: z.number().nullable(),
  keywords: z.array(z.string()),
  language: z.string(),
  source_confidence: confidenceSchema,
  review_status: reviewStatusSchema,
  last_checked_at: z.string().datetime(),
  last_changed_at: z.string().datetime(),
  created_at: z.string().datetime(),
  updated_at: z.string().datetime(),
  source_notes: z.string(),
});

export const compactConferenceSeedSchema = z.object({
  id: z.string().min(1),
  slug: z.string().min(1).optional(),
  title: z.string().min(1),
  acronym: z.string().nullable().optional(),
  year: z.number().int().min(2000).max(2100),
  description: z.string().optional(),
  field_tags: z.array(z.string()).optional(),
  theme_tags: z.array(z.string()).optional(),
  organizer: z.string().nullable().optional(),
  website_url: z.string().url(),
  cfp_url: z.string().url().nullable().optional(),
  source_urls: z.array(z.string().url()).optional(),
  country: z.string(),
  city: z.string(),
  venue: z.string().nullable().optional(),
  mode: modeSchema.optional(),
  event_start_date: z.string().nullable().optional(),
  event_end_date: z.string().nullable().optional(),
  submission_deadline: z.string().nullable().optional(),
  abstract_deadline: z.string().nullable().optional(),
  poster_deadline: z.string().nullable().optional(),
  notification_date: z.string().nullable().optional(),
  camera_ready_deadline: z.string().nullable().optional(),
  registration_deadline: z.string().nullable().optional(),
  early_bird_deadline: z.string().nullable().optional(),
  fees: z.array(feeSchema).optional(),
  currency: z.string().nullable().optional(),
  student_fee: z.number().nullable().optional(),
  regular_fee: z.number().nullable().optional(),
  virtual_fee: z.number().nullable().optional(),
  keywords: z.array(z.string()).optional(),
  language: z.string().optional(),
  source_confidence: confidenceSchema.optional(),
  review_status: reviewStatusSchema.optional(),
  last_checked_at: z.string().datetime().optional(),
  last_changed_at: z.string().datetime().optional(),
  created_at: z.string().datetime().optional(),
  updated_at: z.string().datetime().optional(),
  source_notes: z.string().optional(),
});

export const sourceRegistryEntrySchema = z.object({
  id: z.string().min(1),
  name: z.string().min(1),
  homepage_url: z.string().url(),
  scope: z.string(),
  status: z.enum(["approved_seed", "candidate_needs_review", "excluded"]),
  language_policy: z.string(),
  risk_notes: z.string(),
  parser_difficulty: z.enum(["low", "medium", "high"]),
  likely_fields: z.array(z.string()),
});

export type Conference = z.infer<typeof conferenceSchema>;
export type CompactConferenceSeed = z.infer<typeof compactConferenceSeedSchema>;
export type SourceRegistryEntry = z.infer<typeof sourceRegistryEntrySchema>;
